# Uncomment this line to define a global platform for your project
workspace ’WebViewJavascriptBridge.xcworkspace'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
inhibit_all_warnings!
# Uncomment this line if you're using Swift
use_frameworks!

def pods
pod 'WebViewJavascriptBridge', '~> 6.0'
   end

target 'WebViewJavascriptBridge' do
    pods
end

